- block:
    - name: Mac | Ensure supervisor
      homebrew: name=supervisor
    - name: Mac | Ensure user directory 'LaunchAgents'
      file: name="{{ ansible_env.HOME }}/Library/LaunchAgents" state=directory
    - name: Mac | Ensure supervisord launch agent
      template: src="homebrew.mxcl.supervisor.plist.j2" dest="{{ ansible_env.HOME }}/Library/LaunchAgents/homebrew.mxcl.supervisor.plist"
      notify: Restart supervisor on {{ ansible_os_family }}
  when: ansible_os_family == "Darwin"

- block:
    - name: Debian | Ensure supervisor
      apt: name=supervisor

    - name: Debian | Enable supervisor service
      service: name=supervisor enabled=yes state=started use=service
  when: ansible_os_family == "Debian"
  tags:
    - status
    - supervisor

- name: Ensure directory supervisor.d
  file: name="{{ supervisor.conf_d }}" state=directory

- name: Ensure supervisord configuration
  template: src="supervisord_{{ ansible_os_family }}.conf.j2" dest="{{ supervisor.conf }}" backup=yes
  notify: Restart supervisor on {{ ansible_os_family }}
  tags:
    - config
    - supervisor
  
- name: "Ensure supervisor {{ supervisor.name }} configuration"
  template: src="program.conf.j2" dest="{{ supervisor.conf_d }}/{{ supervisor.name }}.conf" backup=yes
  when: supervisor.disable == false and supervisor.name is defined
  notify: Reload supervisor configuration on {{ ansible_os_family }}
  tags:
    - config
    - supervisor
    - supervisor_conf
