- name: Ensure supervisor
  homebrew: name=supervisor
  when: ansible_os_family == "Darwin"

- name: Ensure supervisor
  apt: name=supervisor
  when: ansible_os_family == "Debian"

- name: Ensure directory supervisor.d
  file: name="{{ supervisor.conf_d }}" state=directory

- name: Ensure supervisord configuration
  template: src="supervisord.conf.j2" dest="{{ supervisor.conf }}" backup=yes
  notify: Reload supervisor configuration
  
- name: "Ensure supervisor {{ supervisor.name }} configuration"
  template: src="program.conf.j2" dest="{{ supervisor.conf_d }}/{{ supervisor.name }}.conf" backup=yes
  notify: Reload supervisor configuration
  tags:
    - config

- block:
    - name: Ensure user directory 'LaunchAgents'
      file: name="{{ ansible_env.HOME }}/Library/LaunchAgents" state=directory
    - name: Ensure supervisord launch agent
      template: src="homebrew.mxcl.supervisor.plist.j2" dest="{{ ansible_env.HOME }}/Library/LaunchAgents/homebrew.mxcl.supervisor.plist"
      notify: Restart supervisor launch agent
  when: ansible_os_family == "Darwin"
  
